customer_homepage:
    path:     /
    defaults: { _controller: CustomerBundle:Home:index }

customer_about:
    path:     /about
    defaults: { _controller: CustomerBundle:About:index }

customer_about_us:
    path:     /about-us
    defaults: { _controller: CustomerBundle:AboutUS:index }

customer_faq:
    path:     /faq
    defaults: { _controller: CustomerBundle:FAQ:index }

customer_flow:
    path:     /flow
    defaults: { _controller: CustomerBundle:Flow:index }

customer_news:
    path:     /news
    defaults: { _controller: CustomerBundle:News:index }

customer_merrit:
    path:     /merrit
    defaults: { _controller: CustomerBundle:Merrit:index }

customer_function:
    path:     /function
    defaults: { _controller: CustomerBundle:Function:index }

customer_contact:
    path:     /contact
    defaults: { _controller: CustomerBundle:Contact:index }

customer_contact_2:
    path:     /contact-2
    defaults: { _controller: CustomerBundle:Contact2:index }

customer_contact_3:
    path:     /contact-3
    defaults: { _controller: CustomerBundle:Contact3:index }

customer_portfolio:
    path:     /portfolio
    defaults: { _controller: CustomerBundle:Portfolio:index }


customer_security_forgot:
    path:     /security/{id}/forgot
    defaults: { _controller: CustomerBundle:Security:forgot }

customer_coupon_link:
    path:     /coupon/link/{id}
    defaults: { _controller: CustomerBundle:Coupon:link }

customer_setting_contact:
    path:     /setting/contact
    defaults: { _controller: CustomerBundle:Setting:contact }

customer_setting_term:
    path:     /setting/term
    defaults: { _controller: CustomerBundle:Setting:term }

customer_setting_trade:
    path:     /setting/trade
    defaults: { _controller: CustomerBundle:Setting:trade}

customer_setting_privacy:
    path:     /setting/privacy
    defaults: { _controller: CustomerBundle:Setting:privacy }