services:
    pon.manager.app_user:
        class: CoreBundle\Manager\AppUserManager
        factory_service:  doctrine
        factory_method:   getEntityManager
        arguments: ["@doctrine.orm.entity_manager", "CoreBundle\\Entity\\AppUser"]
        calls:
            - [setPagination, ["@pon.paginator.pagination"]]

    pon.manager.client:
        class: CoreBundle\Manager\ClientManager
        factory_service:  doctrine
        factory_method:   getEntityManager
        arguments: ["@doctrine.orm.entity_manager", "CoreBundle\\Entity\\Client"]

    pon.manager.store_type:
        class: CoreBundle\Manager\StoreTypeManager
        factory_service:  doctrine
        factory_method:   getEntityManager
        arguments: ["@doctrine.orm.entity_manager", "CoreBundle\\Entity\\StoreType"]
        calls:
            - [setPagination, ["@pon.paginator.pagination"]]
    pon.manager.store:
        class: CoreBundle\Manager\StoreManager
        factory_service:  doctrine
        factory_method:   getEntityManager
        arguments: ["@doctrine.orm.entity_manager", "CoreBundle\\Entity\\Store"]
        calls:
            - [setPagination, ["@pon.paginator.pagination"]]
    pon.manager.user:
        class: CoreBundle\Manager\UserManager
        factory_service:  doctrine
        factory_method:   getEntityManager
        arguments: ["@doctrine.orm.entity_manager", "CoreBundle\\Entity\\User"]
        calls:
            - [setPagination, ["@pon.paginator.pagination"]]

    pon.manager.coupon_type:
        class: CoreBundle\Manager\CouponTypeManager
        factory_service:  doctrine
        factory_method:   getEntityManager
        arguments: ["@doctrine.orm.entity_manager", "CoreBundle\\Entity\\CouponType"]
        calls:
            - [setPagination, ["@pon.paginator.pagination"]]

    pon.dummy.client:
        class: CoreBundle\DummyData\ClientDummy
        calls:
            - [setManager, ["@pon.manager.client"]]

    pon.dummy.app_user:
        class: CoreBundle\DummyData\AppUserDummy
        calls:
            - [setManager, ["@pon.manager.app_user"]]

    pon.exception.exception_handler:
        class: CoreBundle\Exception\ExceptionHandler
        arguments: ["@validator", "@translator"]

    pon.utils.data:
        class: CoreBundle\Utils\Data

    pon.serializator.serializer:
        class: CoreBundle\Serializator\Serializer
        arguments: ["@serializer"]

    pon.paginator.pagination:
        class: CoreBundle\Paginator\Pagination

    pon.queue.consumer.scrapping:
            class: CoreBundle\Queue\Consumer\ScrappingConsumer

    pon.queue.producer.scrapping:
        class: CoreBundle\Queue\Producer\DelayedProducer
        arguments:
            - "@old_sound_rabbit_mq.connection.default"
            - expire_offer
            - delay