services:
    pon.manager.user:
        class: CoreBundle\Manager\UserManager
        factory_service:  doctrine
        factory_method:   getEntityManager
        arguments: ["@doctrine.orm.entity_manager", "CoreBundle\\Entity\\User"]

    pon.manager.client:
        class: CoreBundle\Manager\ClientManager
        factory_service:  doctrine
        factory_method:   getEntityManager
        arguments: ["@doctrine.orm.entity_manager", "CoreBundle\\Entity\\Client"]

    pon.dummy.client:
        class: CoreBundle\DummyData\ClientDummy
        calls:
            - [setManager, ["@pon.manager.client"]]

    pon.queue.consumer.scrapping:
            class: CoreBundle\Queue\Consumer\ScrappingConsumer

    pon.queue.producer.scrapping:
        class: CoreBundle\Queue\Producer\DelayedProducer
        arguments:
            - "@old_sound_rabbit_mq.connection.default"
            - expire_offer
            - delay