CoreBundle\Entity\AppUser:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username]
            message: app_user.username.unique
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: app_user.email.unique
    properties:
        name:
            - Length:
                min: 1
                max: 100
                minMessage: app_user.name.min_message
                maxMessage: app_user.name.max_message
        username:
            - NotBlank:
                message: app_user.username.not_blank
            - Length:
                min: 1
                max: 180
                minMessage: app_user.username.min_message
                maxMessage: app_user.username.max_message
        email:
            - Email:
                message: app_user.email.email
                checkMX: false
            - Length:
                min: 1
                max: 180
                minMessage: app_user.email.min_message
                maxMessage: app_user.email.max_message
        password:
            - NotBlank:
                message: app_user.password.not_blank
            - Length:
                min: 1
                max: 180
                minMessage: app_user.password.min_message
                maxMessage: app_user.password.max_message
        address:
            - Length:
                min: 1
                max: 255
                minMessage: app_user.address.min_message
                maxMessage: app_user.address.max_message
        gender:
            - Choice:
                choices:  [0,1,2]
                message:  app_user.gender.choice
        avatarUrl:
            - Length:
                min: 1
                max: 255
                minMessage: app_user.avatar_url.min_message
                maxMessage: app_user.avatar_url.max_message
        file:
            - Image:
                maxSize: 5024k