CoreBundle\Entity\Category:
    properties:
        name:
            - NotBlank:
                message: category.name.not_blank
            - Length:
                min: 1
                max: 100
                minMessage: category.name.min_message
                maxMessage: category.name.max_message

        imageFile:
            - Image:
                maxSize: 5024k
                maxSizeMessage: category.file.max_size
                mimeTypesMessage: category.file.type