CoreBundle\Entity\Category:
    properties:
        name:
            - NotBlank:
                message: category.name.not_blank
            - Length:
                min: 1
                max: 100
                minMessage: category.name.min_message
                maxMessage: category.name.max_message

        iconUrl:
            - NotBlank:
                message: category.iconUrl.not_blank
            - Length:
                min: 1
                max: 255
                minMessage: category.iconUrl.min_message
                maxMessage: category.iconUrl.max_message
        store:
            - NotBlank:
                message: category.store.not_blank