CoreBundle\Entity\Coupon:
    properties:
        title:
            - Length:
                min: 1
                max: 255
                minMessage: coupon.title.min_message
                maxMessage: coupon.title.max_message
        imageFile:
            - Image:
                maxSize: 5024k
                maxSizeMessage: coupon.file.max_size
                mimeTypesMessage: coupon.file.type
        couponPhotos:
            - Valid: ~
        couponUserPhotos:
            - Valid: ~