CoreBundle\Entity\News:
    properties:
        title:
            - NotBlank:
                message: news.title.not_blank
            - Length:
                min: 1
                max: 255
                minMessage: news.title.min_message
                maxMessage: news.title.max_message