CoreBundle\Entity\Store:
    properties:
        title:
            - Length:
                min: 1
                max: 255
                minMessage: store.title.min_message
                maxMessage: store.title.max_message
        latitude:
            - Length:
                min: 1
                max: 20
                minMessage: store.latitude.min_message
                maxMessage: store.latitude.max_message
        longitude:
            - Length:
                min: 1
                max: 20
                minMessage: store.longtitude.min_message
                maxMessage: store.longtitude.max_message