CoreBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username]
            message: user.username.unique
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: user.email.unique
    properties:
        username:
            - NotBlank:
                message: user.username.not_blank
            - Length:
                min: 1
                max: 180
                minMessage: user.username.min_message
                maxMessage: user.username.max_message
        email:
            - NotBlank:
                message: user.email.not_blank
            - Email:
                message: app_user.email.email
                checkMX: false
            - Length:
                min: 1
                max: 180
                minMessage: user.email.min_message
                maxMessage: user.email.max_message
        plainPassword:
            - NotBlank:
                message: user.plain_password.not_blank
            - Length:
                min: 1
                max: 180
                minMessage: user.plain_password.min_message
                maxMessage: user.plain_password.max_message
        fullName:
            - NotBlank:
                message: user.full_name.not_blank
            - Length:
                min: 1
                max: 255
                minMessage: user.full_name.min_message
                maxMessage: user.full_name.max_message
        sex:
            - NotBlank:
                message: user.sex.not_blank
            - Choice:
                choices:  [0, 1]
                message:  user.sex.choice
        birthday:
            - NotBlank:
                message: user.birthday.not_blank
            - Date:
                message: user.birthday.date
        locale:
            - NotBlank:
                message: user.locale.not_blank
            - Length:
                min: 1
                max: 5
                minMessage: user.locale.min_message
                maxMessage: user.locale.max_message
        temporaryHash:
            - NotBlank:
                message: user.temporary_hash.not_blank
            - Length:
                min: 1
                max: 5
                minMessage: user.temporary_hash.min_message
                maxMessage: user.temporary_hash.max_message
        rememberToken:
            - NotBlank:
                message: user.remember_token.not_blank
            - Length:
                min: 1
                max: 100
                minMessage: user.remember_token.min_message
                maxMessage: user.remember_token.max_message
        company:
            - NotBlank:
                message: user.company.not_blank
            - Length:
                min: 1
                max: 255
                minMessage: user.company.min_message
                maxMessage: user.company.max_message
        address:
            - NotBlank:
                message: user.address.not_blank
            - Length:
                min: 1
                max: 255
                minMessage: user.address.min_message
                maxMessage: user.address.max_message
        tel:
            - NotBlank:
                message: user.tel.not_blank
            - Length:
                min: 1
                max: 20
                minMessage: user.tel.min_message
                maxMessage: user.tel.max_message
        imageUser:
            - NotBlank:
                message: user.image_user.not_blank
            - Length:
                min: 1
                max: 255
                minMessage: user.image_user.min_message
                maxMessage: user.image_user.max_message