admin_management:
    path:     /management
    defaults: { _controller: AdminBundle:Management:index }

admin_dashboard:
    path:     /
    defaults: { _controller: AdminBundle:Dashboard:index }

admin_coupon_link:
    path:     /coupon/link/{id}
    defaults: { _controller: AdminBundle:Coupon:link }

admin_summary:
    path:     /summary
    defaults: { _controller: AdminBundle:Summary:index }

admin_summary_edit:
    path:     /summary/edit/{id}
    defaults: { _controller: AdminBundle:Summary:edit }

admin_push:
    path:     /push
    defaults: { _controller: AdminBundle:Push:index }

admin_analytic:
    path:     /analytic
    defaults: { _controller: AdminBundle:Analytic:index }

admin_customer:
    path:     /customer
    defaults: { _controller: AdminBundle:Customer:index }

admin_news:
    path:     /news
    defaults: { _controller: AdminBundle:News:index }

admin_setting:
    path:     /setting
    defaults: { _controller: AdminBundle:Setting:index }

admin_help:
    path:     /help
    defaults: { _controller: AdminBundle:Help:index }

admin_contact:
    path:     /contact
    defaults: { _controller: AdminBundle:Contact:index }

admin_login:
    path:     /login
    defaults: { _controller: AdminBundle:Security:login }

admin_register:
    path:     /register
    defaults: { _controller: AdminBundle:Security:register }

admin_logout:
    path:     /logout
    defaults: { _controller: AdminBundle:Security:logout }

admin_forgot:
    path:     /forgot
    defaults: { _controller: AdminBundle:Security:forgot }

admin_store_search:
    path:     /store/search
    defaults: { _controller: AdminBundle:Store:search }