admin_management:
    path:     /management
    defaults: { _controller: AdminBundle:Management:index }

admin_dashboard:
    path:     /
    defaults: { _controller: AdminBundle:Dashboard:index }

admin_coupon_link:
    path:     /coupon/link/{id}
    defaults: { _controller: AdminBundle:Coupon:link }

admin_app_user:
    path:     /user
    defaults: { _controller: AdminBundle:AppUser:index }

admin_app_user_create:
    path:     /user/create
    defaults: { _controller: AdminBundle:AppUser:create }

admin_app_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: AdminBundle:AppUser:edit }

admin_app_user_active:
    path:     /user/active/{id}
    defaults: { _controller: AdminBundle:AppUser:active }

admin_summary:
    path:     /summary
    defaults: { _controller: AdminBundle:Summary:index }

admin_summary_create:
    path:     /summary/create
    defaults: { _controller: AdminBundle:Summary:create }

admin_summary_edit:
    path:     /summary/edit/{id}
    defaults: { _controller: AdminBundle:Summary:edit }

admin_category:
    path:     /category
    defaults: { _controller: AdminBundle:Category:index }

admin_category_create:
    path:     /category/create
    defaults: { _controller: AdminBundle:Category:create }

admin_news_category:
    path:     /news-category
    defaults: { _controller: AdminBundle:NewsCategory:index }

admin_news_category_create:
    path:     /news-category/create
    defaults: { _controller: AdminBundle:NewsCategory:create }

admin_news_category_edit:
    path:     /news-category/edit/{id}
    defaults: { _controller: AdminBundle:NewsCategory:edit }

admin_category_edit:
    path:     /category/edit/{id}
    defaults: { _controller: AdminBundle:Category:edit }

admin_store:
    path:     /store
    defaults: { _controller: AdminBundle:Store:index }

admin_store_create:
    path:     /store/create
    defaults: { _controller: AdminBundle:Store:create }

admin_store_edit:
    path:     /store/edit/{id}
    defaults: { _controller: AdminBundle:Store:edit }

admin_push:
    path:     /push
    defaults: { _controller: AdminBundle:Push:index }

admin_push_update:
    path:     /push/update
    defaults: { _controller: AdminBundle:Push:create }

admin_push_edit:
    path:     /push/edit/{id}
    defaults: { _controller: AdminBundle:Push:edit }

admin_create:
    path:     /push/create
    defaults: { _controller: AdminBundle:Push:create }

admin_analytic:
    path:     /analytic
    defaults: { _controller: AdminBundle:Analytic:index }

admin_customer:
    path:     /customer
    defaults: { _controller: AdminBundle:Customer:index }

admin_customer_active:
    path:     /user/customer/{id}
    defaults: { _controller: AdminBundle:Customer:active }

admin_customer_view:
    path:     /user/customer/{id}/view
    defaults: { _controller: AdminBundle:Customer:view }

admin_news:
    path:     /news
    defaults: { _controller: AdminBundle:News:index }

admin_news_create:
    path:     /news/create
    defaults: { _controller: AdminBundle:News:create }

admin_news_edit:
    path:     /news/edit/{id}
    defaults: { _controller: AdminBundle:News:edit }

admin_setting:
    path:     /setting
    defaults: { _controller: AdminBundle:Setting:index }

admin_setting_store:
    path:     /setting/store
    defaults: { _controller: AdminBundle:Setting:editStore }

admin_help:
    path:     /help
    defaults: { _controller: AdminBundle:Help:index }

admin_contact:
    path:     /contact
    defaults: { _controller: AdminBundle:Contact:index }

admin_login:
    path:     /login
    defaults: { _controller: AdminBundle:Security:login }

admin_register:
    path:     /register
    defaults: { _controller: AdminBundle:Security:register }

admin_logout:
    path:     /logout
    defaults: { _controller: AdminBundle:Security:logout }

admin_forgot:
    path:     /forgot
    defaults: { _controller: AdminBundle:Security:forgot }

admin_store_search:
    path:     /store/search
    defaults: { _controller: AdminBundle:Store:search }

admin_category_search:
    path:     /category/search
    defaults: { _controller: AdminBundle:Category:search }

admin_news_category_search:
    path:     /news-category/search
    defaults: { _controller: AdminBundle:NewsCategory:search }