services:
    pon.twig.pager_extension:
        class: AdminBundle\Twig\PagerExtension
        arguments:
            - '@router'
        tags:
            - { name: twig.extension }
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
