services:
    pon.twig.pager_extension:
        class: AdminBundle\Twig\PagerExtension
        arguments:
            - '@router'
        tags:
            - { name: twig.extension }
    pon.form.extension.collection:
        class: AdminBundle\Form\Extension\CollectionTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CollectionType }
