services:
    pon.twig.pager_extension:
        class: AdminBundle\Twig\PagerExtension
        arguments:
            - '@router'
        tags:
            - { name: twig.extension }
    pon.form.extension.collection:
        class: AdminBundle\Form\Extension\CollectionTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CollectionType }

    pon.form.type.store:
        class: AdminBundle\Form\Type\StoreSearchType
        calls:
            - [setManager, ['@pon.manager.store']]
        tags:
            -  { name: form.type, alias:'store_search' }

    pon.form.type.category:
        class: AdminBundle\Form\Type\CategorySearchType
        calls:
            - [setManager, ['@pon.manager.category']]
        tags:
            -  { name: form.type, alias:'category_search' }

    pon.form.type.news_category:
        class: AdminBundle\Form\Type\NewsCategorySearchType
        calls:
            - [setManager, ['@pon.manager.news_category']]
        tags:
            -  { name: form.type, alias:'news_category_search' }