app_app_user:
    prefix: /v1
    type: rest
    resource: AppBundle\Controller\AppUserController
    name_prefix: api_app_user

app_store:
    prefix: /v1
    type: rest
    resource: AppBundle\Controller\StoreController
    name_prefix: api_store

app_category:
    prefix: /v1
    type: rest
    resource: AppBundle\Controller\CategoryController
    name_prefix: api_coupon_type

app_coupon:
    prefix: /v1
    type: rest
    resource: AppBundle\Controller\CouponController
    name_prefix: api_coupon

app_post:
    prefix: /v1
    type: rest
    resource: AppBundle\Controller\PostController
    name_prefix: api_post

app_news:
    prefix: /v1
    type: rest
    resource: AppBundle\Controller\NewsController
    name_prefix: api_news

app_setting:
    prefix: /v1
    type: rest
    resource: AppBundle\Controller\SettingController
    name_prefix: api_setting