imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: rabbitmq.yml }
    - { resource: elasticsearch.yml }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@CustomerBundle/Resources/config/services.yml" }
    - { resource: "@LandingPageBundle/Resources/config/services.yml" }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@CoreBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        coupon_types: '%coupon_types%'
        base_image_upload: '%base_image_upload%'
        coupon_avatar_path: %base_coupon_avatar_path%
        user_avatar_path: %base_user_avatar_path%
        category_avatar_path: %base_category_avatar_path%
        news_category_avatar_path: %base_news_category_avatar_path%
        store_avatar_path: %base_store_avatar_path%
        genders: %genders%
        news_avatar_path: %base_news_avatar_path%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

monolog:
    channels:
        - scrapping
        - sync_post

# app/config/config.yml
nelmio_api_doc: ~

fos_user:
    db_driver: orm
    firewall_name: api                                  # Seems to be used when registering user/reseting password,
                                                        # but since there is no "login", as so it seems to be useless in
                                                        # our particular context, but still required by "FOSUserBundle"
    user_class: CoreBundle\Entity\AppUser

fos_oauth_server:
    db_driver:           orm
    client_class:        CoreBundle\Entity\Client
    access_token_class:  CoreBundle\Entity\AccessToken
    refresh_token_class: CoreBundle\Entity\RefreshToken
    auth_code_class:     CoreBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username             # This property will be used when valid credentials are given to load the user upon access token creation

fos_rest:
    param_fetcher_listener: true
    versioning: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
        templating_formats:
            html: false
    routing_loader:
        default_format: json
        include_format: false
    access_denied_listener:
        json: true
    disable_csrf_role: ROLE_API

    serializer:
        serialize_null: true
    exception:
        codes:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': 400
            'Symfony\Component\HttpKernel\Exception\ConflictHttpException': 409
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
            'Symfony\Component\Security\Core\Exception\AuthenticationException': 401
        messages:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': true
            'Symfony\Component\HttpKernel\Exception\ConflictHttpException': true
            'Symfony\Component\Security\Core\Exception\AuthenticationException': true


jms_serializer:
    metadata:
        directories:
            CORESUB:
                namespace_prefix: "CoreBundle"
                path: "@CoreBundle/Resources/config/serializer"
            FOSSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "@CoreBundle/Resources/config/serializer"