fos_elastica:
    clients:
        default: { host: '%elasticsearch_host%', port: '%elasticsearch_port%' }
    indexes:
        app:
            index_name: '%elasticsearch_index%'
            types:
                appUser:
                    mappings:
                        id: ~
                        username: ~
                        roles: ~
                        useLists:
                            type: "nested"
                            properties:
                                coupon:
                                    type: object
                                    properties:
                                        id: ~
                                        title: ~
                                        imageUrl: ~
                                status: ~
                                expiredTime:
                                    type: date
                                createdAt:
                                    type: date
                                code: ~
                        likeLists:
                            type: "nested"
                            properties:
                                coupon:
                                    type: object
                                    properties:
                                        id: ~
                                        title: ~
                                        imageUrl: ~
                        followLists:
                            type: "nested"
                            properties:
                                store:
                                    type: object
                                    properties:
                                        id: ~
                                        title: ~
                                        avatarUrl: ~
                                        address: ~
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\AppUser
                        provider: ~
                        listener: ~
                        finder: ~
                store:
                    mappings:
                        id: ~
                        title: ~
                        operationStartTime:
                            type: date
                        operationEndTime:
                            type: date
                        avatarUrl: ~
                        tel: ~
                        location: {type: geo_point}
                        impression: ~
                        latitude: ~
                        longitude: ~
                        address: ~
                        closeDate: ~
                        aveBill: ~
                        help_text: ~
                        address: ~
                        storePhotos:
                            type: "nested"
                            properties:
                                photo:
                                    type: object
                                    properties:
                                        id: ~
                                        imageUrl: ~
                        category:
                            type: object
                            properties:
                                id: ~
                                name: ~
                                iconUrl: ~
                        appUser:
                            type: object
                            properties:
                                id: ~
                                username: ~
                                email: ~
                        followLists:
                            type: "nested"
                            properties:
                                appUser:
                                    type: object
                                    properties:
                                        id: ~
                                        username: ~
                                        email: ~
                        coupons:
                            type: nested
                            properties:
                                id: ~
                                title: ~
                                imageUrl: ~
                                type: ~
                                impression:
                                    type: integer
                                couponUserPhotos:
                                    type: "nested"
                                    properties:
                                        photo:
                                            type: object
                                            properties:
                                                id: ~
                                                imageUrl: ~
                                couponPhotos:
                                    type: "nested"
                                    properties:
                                        photo:
                                            type: object
                                            properties:
                                                id: ~
                                                imageUrl: ~
                                useLists:
                                    type: nested
                                    properties:
                                        appUser:
                                            type: object
                                            properties:
                                                id: ~
                                                username: ~
                                                email: ~
                                        status: ~
                                        expiredTime:
                                            type: date
                                        createdAt:
                                            type: date
                                        code: ~
                                likeLists:
                                    type: "nested"
                                    properties:
                                        appUser:
                                            type: object
                                            properties:
                                                id: ~
                                                username: ~
                                                email: ~
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        deletedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\Store
                        provider: ~
                        listener: ~
                        finder: ~
                coupon:
                    mappings:
                        id: ~
                        title: ~
                        expiredTime:
                            type: date
                        imageUrl: ~
                        needLogin: ~
                        impression: ~
                        type: ~
                        description: ~
                        status:
                            type: boolean
                        size: ~
                        couponUserPhotos:
                            type: "nested"
                            properties:
                                photo:
                                    type: object
                                    properties:
                                        id: ~
                                        imageUrl: ~
                        couponPhotos:
                            type: "nested"
                            properties:
                                photo:
                                    type: object
                                    properties:
                                        id: ~
                                        imageUrl: ~
                        store:
                            type: object
                            properties:
                                id: ~
                                title: ~
                                location: {type: geo_point}
                                latitude: ~
                                longitude: ~
                                address: ~
                                impression: ~
                                storePhotos:
                                    type: "nested"
                                    properties:
                                        photo:
                                            type: object
                                            properties:
                                                id: ~
                                                imageUrl: ~
                                appUser:
                                    type: object
                                    properties:
                                        id: ~
                                        username: ~
                                        email: ~
                                category:
                                    type: object
                                    properties:
                                        id: ~
                                        name: ~
                                        iconUrl: ~
                        useLists:
                            type: nested
                            properties:
                                appUser:
                                    type: object
                                    properties:
                                        id: ~
                                        username: ~
                                        email: ~
                                status: ~
                                expiredTime:
                                    type: date
                                createdAt:
                                    type: date
                                code: ~
                        likeLists:
                            type: nested
                            properties:
                                appUser:
                                    type: object
                                    properties:
                                        id: ~
                                        username: ~
                                        email: ~
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        deletedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\Coupon
                        provider: ~
                        listener: ~
                        finder: ~
                category:
                    mappings:
                        id: ~
                        name: ~
                        iconUrl: ~
                        stores:
                            type: "nested"
                            properties:
                                id: ~
                                title: ~
                                address: ~
                                coupons:
                                    type: nested
                                    properties:
                                        id: ~
                                        title: ~
                                        imageUrl: ~
                                        expiredTime:
                                            type: date
                                        type: ~
                                        needLogin: ~
                                        impression:
                                            type: integer
                                        createdAt:
                                            type: date
                                        updatedAt:
                                            type: date
                                        deletedAt:
                                            type: date
                                        likeLists:
                                            type: "nested"
                                            properties:
                                                appUser:
                                                    type: object
                                                    properties:
                                                        id: ~
                                                        username: ~
                                                        email: ~
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\Category
                        provider: ~
                        listener: ~
                        finder: ~

                useList:
                    mappings:
                        id: ~
                        coupon:
                            type: object
                            properties:
                                id: ~
                                title: ~
                        appUser:
                            type: object
                            properties:
                                id: ~
                                username: ~
                                name: ~
                        expiredTime:
                            type: date
                        createdAt:
                            type: date
                        status: ~
                        code: ~
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\UseList
                        provider: ~
                        listener: ~
                        finder: ~