fos_elastica:
    clients:
        default: { host: '%elasticsearch_host%', port: '%elasticsearch_port%' }
    indexes:
        app:
            index_name: '%elasticsearch_index%'
            settings:
                index:
                    analysis:
                        analyzer:
                            keyword_analyzer :
                                type     :    custom
                                tokenizer:    keyword
                                filter   :    [lowercase]
            types:
                appUser:
                    mappings:
                        id: ~
                        username: ~
                        roles: ~
                        usernameCanonical: ~
                        email: ~
                        emailCanonical: ~
                        name: ~
                        enabled: ~
                        address: ~
                        company: ~
                        tel: ~
                        avatarUrl: ~
                        store:
                            type: object
                                properties:
                                    id: ~
                                    title: ~
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        deletedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\AppUser
                        provider: ~
                        listener: ~
                        finder: ~
                store:
                    mappings:
                        id: ~
                        title: ~
                        operationStartTime:
                            type: date
                        operationEndTime:
                            type: date
                        avatarUrl: ~
                        tel: ~
                        location: {type: geo_point}
                        impression: ~
                        latitude: ~
                        longitude: ~
                        address: ~
                        closeDate: ~
                        aveBill: ~
                        help_text: ~
                        address: ~
                        category:
                            type: object
                            properties:
                                id: ~
                                name: ~
                                iconUrl: ~
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        deletedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\Store
                        provider: ~
                        listener: ~
                        finder: ~
                coupon:
                    mappings:
                        id: ~
                        couponId:
                            type: string
                            index: not_analyzed
                        title: ~
                        expiredTime:
                            type: date
                        imageUrl: ~
                        needLogin: ~
                        impression: ~
                        type: ~
                        description: ~
                        hashTag: ~
                        status:
                            type: boolean
                        size: ~
                        store:
                            type: object
                            properties:
                                id: ~
                                title: ~
                                location: {type: geo_point}
                                latitude: ~
                                longitude: ~
                                address: ~
                                impression: ~
                                appUser:
                                    type: object
                                    properties:
                                        id: ~
                                        username: ~
                                        email: ~
                                category:
                                    type: object
                                    properties:
                                        id: ~
                                        name: ~
                                        iconUrl: ~
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        deletedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\Coupon
                        provider: ~
                        listener: ~
                        finder: ~

                storePhoto:
                    mappings:
                        store:
                            type: object
                            properties:
                                id: ~
                                title: ~
                        photo:
                            type: object
                            properties:
                                id: ~
                                imageUrl: ~
                                photoId:
                                    type: string
                                    index_analyzer: keyword_analyzer
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\StorePhoto
                        provider: ~
                        listener: ~
                        finder: ~

                couponUserPhoto:
                    mappings:
                        coupon:
                            type: object
                            properties:
                                id: ~
                                couponId:
                                    type: string
                                    index_analyzer: keyword_analyzer
                                title: ~
                        photo:
                            type: object
                            properties:
                                id: ~
                                imageUrl: ~
                                photoId:
                                    type: string
                                    index_analyzer: keyword_analyzer
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\CouponUserPhoto
                        provider: ~
                        listener: ~
                        finder: ~

                couponPhoto:
                    mappings:
                        coupon:
                            type: object
                            properties:
                                id: ~
                                couponId:
                                    type: string
                                    index_analyzer: keyword_analyzer
                                title: ~
                        photo:
                            type: object
                            properties:
                                id: ~
                                imageUrl: ~
                                photoId:
                                    type: string
                                    index_analyzer: keyword_analyzer
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\CouponPhoto
                        provider: ~
                        listener: ~
                        finder: ~

                category:
                    mappings:
                        id: ~
                        name: ~
                        iconUrl: ~
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\Category
                        provider: ~
                        listener: ~
                        finder: ~

                useList:
                    mappings:
                        id: ~
                        coupon:
                            type: object
                            properties:
                                id: ~
                                couponId:
                                    type: string
                                    index_analyzer: keyword_analyzer
                                title: ~
                                hashTag: ~
                                deletedAt:
                                    type: date
                                store:
                                    type: object
                                    properties:
                                        id: ~
                                        title: ~
                                        deletedAt:
                                            type: date
                                        category:
                                            type: object
                                            properties:
                                                id: ~
                                                name: ~
                                                iconUrl: ~
                                        appUser:
                                            type: object
                                            properties:
                                                id: ~
                        appUser:
                            type: object
                            properties:
                                id: ~
                                username: ~
                                name: ~
                        requestedAt:
                            type: date
                        expiredTime:
                            type: date
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        status: ~
                        code:
                            type: string
                            index_analyzer: keyword_analyzer
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\UseList
                        provider: ~
                        listener: ~
                        finder: ~

                followList:
                    mappings:
                        id: ~
                        store:
                            type: object
                            properties:
                                id: ~
                                title: ~
                                avatar_url: ~
                                deletedAt:
                                    type: date
                        appUser:
                            type: object
                            properties:
                                id: ~
                                username: ~
                                name: ~
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\FollowList
                        provider: ~
                        listener: ~
                        finder: ~

                likeList:
                    mappings:
                        id: ~
                        coupon:
                            type: object
                            properties:
                                id: ~
                                couponId:
                                    type: string
                                    index_analyzer: keyword_analyzer
                                title: ~
                                imageUrl: ~
                                deletedAt:
                                    type: date
                        appUser:
                            type: object
                            properties:
                                id: ~
                                username: ~
                                name: ~
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\LikeList
                        provider: ~
                        listener: ~
                        finder: ~

                segement:
                    mappings:
                        id: ~
                        title: ~
                        store:
                            type: object
                            properties:
                                id: ~
                                title: ~
                                deletedAt:
                                    type: date
                                appUser:
                                    type: object
                                    properties:
                                        id: ~
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        deletedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\Segement
                        provider: ~
                        listener: ~
                        finder: ~

                pushSetting:
                    mappings:
                        id: ~
                        store:
                            type: object
                            properties:
                                id: ~
                                title: ~
                                avatar_url: ~
                                deletedAt:
                                    type: date
                                appUser:
                                    type: object
                                    properties:
                                        id: ~
                        segement:
                            type: object
                            properties:
                                id: ~
                        title: ~
                        message: ~
                        status: ~
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        deletedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\PushSetting
                        provider: ~
                        listener: ~
                        finder: ~

                messageDelivery:
                    mappings:
                        id: ~
                        pushSetting:
                            type: object
                            properties:
                                id: ~
                        status: ~
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\MessageDelivery
                        provider: ~
                        listener: ~
                        finder: ~

                socialProfile:
                    mappings:
                        id: ~
                        appUser:
                            type: object
                            properties:
                                id: ~
                                username: ~
                        socialType: ~
                        socialId: ~
                        socialToken: ~
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        deletedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: CoreBundle\Entity\SocialProfile
                        provider: ~
                        listener: ~
                        finder: ~