old_sound_rabbit_mq:
    connections:
        default:
            host:     '%rabbitmq_host%'
            port:     '%rabbitmq_port%'
            user:     '%rabbitmq_user%'
            password: '%rabbitmq_pass%'
            vhost:    '/'
            lazy:     false
            connection_timeout: 60
            read_write_timeout: 60

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
            use_socket: true # default false
    producers:
        scrapping:
            connection:       default
            exchange_options: {name: 'scrapping', type: direct}
            service_alias:    pon_service # no alias by default
    consumers:
        scrapping:
            connection:       default
            exchange_options: {name: 'scrapping', type: direct}
            queue_options:    {name: 'scrapping'}
            callback:         pon.queue.consumer.scrapping