old_sound_rabbit_mq:
    connections:
        default:
            host:     '%rabbitmq_host%'
            port:     '%rabbitmq_port%'
            user:     '%rabbitmq_user%'
            password: '%rabbitmq_pass%'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
            use_socket: false
    producers:
        scrapping:
            connection:       default
            exchange_options: {name: 'scrapping', type: direct}
        sync_post:
            connection:       default
            exchange_options: {name: 'sync_post', type: direct}
        email:
            connection:       default
            exchange_options: {name: 'email', type: direct}
    consumers:
        scrapping:
            connection:       default
            exchange_options: {name: 'scrapping', type: direct}
            queue_options:    {name: 'scrapping'}
            callback:         pon.queue.consumer.scrapping
        sync_post:
            connection:       default
            exchange_options: {name: 'sync_post', type: direct}
            queue_options:    {name: 'sync_post'}
            callback:         pon.queue.consumer.sync_post
        email:
            connection:       default
            exchange_options: {name: 'email', type: direct}
            queue_options:    {name: 'email'}
            callback:         pon.queue.consumer.email