admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

customer:
    resource: "@CustomerBundle/Resources/config/routing.yml"
    prefix:   /

landing_page:
    resource: "@LandingPageBundle/Resources/config/routing.yml"
    prefix:   /lp

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

EndroidQrCodeBundle:
    resource: "@EndroidQrCodeBundle/Controller/"
    type:     annotation
    prefix:   /qrcode
user_context_hash:
    path: /_fos_user_context_hash