admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

customer:
    resource: "@CustomerBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"