# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512
    role_hierarchy:
        ROLE_APP:  ROLE_USER
        ROLE_CLIENT:  ROLE_APP
        ROLE_ADMIN:       ROLE_CLIENT
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username        # fos_user.user_provider.username_email does not seem to work (OAuth-spec related ("username + password") ?)
        in_memory:
            memory: ~

    firewalls:
        admin:
            pattern: ^/admin
            anonymous: ~
            form_login:
                provider: fos_userbundle
                use_forward:    false
                login_path: /admin/login
                check_path: /admin/login
                default_target_path: /admin
                failure_path:   null
                use_referer: true
                require_previous_session: false
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:
            logout:
                path:   /admin/logout
                target: /admin
            anonymous:    true
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        api_news_detail:
            security: true
            pattern: ^/api/v1/news/[0-9]+   # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true
        api_news_list:
            security: true
            pattern: ^/api/v1/news   # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true
        api_search_coupons:
            security: true
            pattern: ^/api/v1/search/coupons   # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true
        api_map_shop_coupons:
            security: true
            pattern: ^/api/v1/map   # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true
        api_featured_shop:
            security: true
            pattern: ^/api/v1/featured/[0-9]+/shops   # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true
        api_featured_shop_type:
            security: true
            pattern: ^/api/v1/featured/[0-9]+/shops/[0-9]+   # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true
        api_shop_detail:
            security: true
            pattern: ^/api/v1/shops/[0-9]+   # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true
        api_category_shop:
            security: true
            pattern: ^/api/v1/category/[0-9]+/shops   # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true
        api_categories:
            security: true
            pattern: ^/api/v1/categories   # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true
        api_featured_category_coupons:
            security: true
            pattern: ^/api/v1/featured/[0-9]+/category/[0-9]+/coupons   # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true
        api_coupon_detail:
            security: true
            pattern: ^/api/v1/coupons/[0-9]+   # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true                           # Anonymous access is not allowed
        api_featured_coupon:
            security: true
            pattern: ^/api/v1/featured/[0-9]+/coupons   # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true                           # Anonymous access is not allowed
        api_forgot_password:
            security: true
            pattern: ^/api/v1/forgot/password                               # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true                           # Anonymous access is not allowed
        api_twitter_signin:
            security: true
            pattern: ^/api/v1/twitter/signin                               # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true                           # Anonymous access is not allowed
        api_instagram_signin:
            security: true
            pattern: ^/api/v1/instagram/signin                               # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true                           # Anonymous access is not allowed
        api_facebook_signin:
            security: true
            pattern: ^/api/v1/facebook/signin                               # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true                           # Anonymous access is not allowed
        api_signin:
            security: true
            pattern: ^/api/v1/signin                               # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true                           # Anonymous access is not allowed
        api_signup:
            security: true
            pattern: ^/api/v1/signup                               # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true                           # Anonymous access is not allowed
        api:
            security: true
            pattern: ^/api/v1                                # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: false                           # Anonymous access is not allowed
        # disables authentication for assets and the profiler, adapt it according to your needs

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

#            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        admin_area_none:
            path: ^/admin/coupon/link
            role: IS_AUTHENTICATED_ANONYMOUSLY
        admin_register:
            path: /admin/register
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        admin_login:
            path: /admin/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        admin_area:
            path: ^/admin
            role: ROLE_USER
