# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
   facebook_config:
       app_id: '%facebook_client_id%'
       app_secret: '%facebook_client_secret%'

   instagram_config:
      apiKey: '%instagram_client_id%'
      apiSecret: '%instagram_client_secret%'
      apiCallback: 'http://localhost'

   coupon_types:
      1: SNS
      2: Store

   genders:
      0: 女性
      1: 男性
      2: その他

   reportTypes:
      sessions: 1
      users: 2
      pageviews: 3
      avgSessionDuration: 4
      bounceRate: 5
      exitRate: 6

   segments:
      all: All
      active_users: Active Users
      engaged_users: Engaged Users
      inactive_users: Inactive Users