CoreBundle\Entity\Store:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [view, list]
        title:
            expose : true
            groups: [view,list]
        operationStartTime:
            expose: true
            groups: [view,list]
            type: DateTime<'H:i'>
        operationEndTime:
            expose: true
            groups: [view,list]
            type: DateTime<'H:i'>
        avatarUrl:
             expose: true
             groups: [view,list]
        follow:
            expose: true
            groups: [view,list]
            serialized_name: is_follow
        latitude:
            expose: true
            groups: [view,list]
        longitude:
            expose: true
            groups: [view,list]
        tel:
            expose: true
            groups: [view,list]
        address:
            expose: true
            groups: [view,list]
        closeDate:
            expose: true
            groups: [view,list]
        aveBill:
            expose: true
            groups: [view,list]
        helpText:
            expose: true
            groups: [view,list]
        shopPhotoUrl:
            expose: true
            groups: [view,list]
        category:
            expose: true
            groups: [view,list]
        coupons:
            expose: true
            groups: [view,list]
        user:
            expose: true
            groups: [view]
        createdAt:
            expose: true
            groups: [view]
        updatedAt:
            expose: true
            groups: [view]