CoreBundle\Entity\News:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [list_news,view_news]
        title:
            expose : true
            groups: [list_news,view_news]
        introduction:
            expose: true
            groups: [list_news,view_news]
        store:
            expose: true
            groups: [list_news,view_news]
            serialized_name: shop
        newsCategory:
            expose: true
            groups: [list_news,view_news]
            serialized_name: category
        createdAt:
            expose: true
            groups: [list_news,view_news]
        description:
            expose: true
            groups: [view_news]
        updatedAt:
            expose: true
            groups: [view_news]