CoreBundle\Entity\Category:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [list_category, featured_coupon,store_category,list_coupon_store]
        name:
            expose : true
            groups: [list_category, featured_coupon, store_category,list_coupon_store]
        coupons:
            expose : true
            groups: [featured_coupon]
        iconUrl:
            expose : true
            groups: [list_category, featured_coupon, store_category,list_coupon_store]