CoreBundle\Entity\Store:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [list_news_store,store_featured,view,view_coupon, list,list_coupon_store]
        title:
            expose : true
            groups: [list_news_store,store_featured,view,view_coupon,list,list_coupon_store]
        link:
            expose : true
            groups: [list_news_store,store_featured,view,view_coupon,list,list_coupon_store]
        operationStartTime:
            expose: true
            groups: [view,view_coupon,list]
            type: DateTime<'H:i'>
        operationEndTime:
            expose: true
            groups: [view,view_coupon,list]
            type: DateTime<'H:i'>
        avatarUrl:
             expose: true
             groups: [store_featured,view,view_coupon,list]
        follow:
            expose: true
            groups: [store_featured,view,view_coupon,list]
            serialized_name: is_follow
        latitude:
            expose: true
            groups: [view,view_coupon,list]
        longitude:
            expose: true
            groups: [view,view_coupon,list]
        tel:
            expose: true
            groups: [view,view_coupon,list]
        impression:
            expose: true
            groups: [view,list]
        address:
            expose: true
            groups: [view,view_coupon,list]
        closeDate:
            expose: true
            groups: [view,view_coupon,list]
        aveBill:
            expose: true
            groups: [view,view_coupon,list]
        helpText:
            expose: true
            groups: [view,view_coupon,list]
        storePhotoUrls:
            expose: true
            groups: [view,view_coupon, list]
            serialized_name: shop_photo_url
        category:
            expose: true
            groups: [view,view_coupon,list,list_coupon_store]
        activeCoupons:
            expose: true
            groups: [view,list]
            serialized_name: coupons
        user:
            expose: true
            groups: [view]
        createdAt:
            expose: true
            groups: [view,view_coupon]
        updatedAt:
            expose: true
            groups: [view,view_coupon]