CoreBundle\Entity\Coupon:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [view,store_coupon]
        title:
            expose: true
            groups: [view,store_coupon]
        imageUrl:
            expose: true
            groups: [view, store_coupon]
        description:
            expose: true
            groups: [view]
        expiredTime:
            expose: true
            groups: [view, store_coupon]
            type: DateTime<'Y-m-d'>
        like:
            expose: true
            groups: [view, store_coupon]
            serialized_name: is_like
        needLogin:
            expose: true
            groups: [view, store_coupon]
        canUse:
            expose: true
            groups: [view, store_coupon]
        couponPhotoUrls:
            expose: true
            groups: [view, store_coupon]
            serialized_name: coupon_photo_url
        couponType:
            expose : true
            groups: [view, store_coupon]
        createdAt:
            expose: true
            groups: [view]
        updatedAt:
            expose: true
            groups: [view]