CoreBundle\Entity\UseList:
    exclusion_policy: ALL
    properties:
        appUser:
            expose: true
            groups: [use_list]
            serialized_name: user
        requestedAt:
            expose: true
            groups: [use_list]
        coupon:
            expose: true
            groups: [use_list]
        code:
            expose: true
            groups: [use_list]