CoreBundle\Entity\AppUser:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [view]
        plainPassword:
            expose : true
            groups: [view]
        temporaryHash:
            expose : true
            groups: [view]
        androidPushKey:
            expose: true
            groups: [view]
        applePushKey:
            expose: true
            groups: [view]
        name:
            expose: true
            groups: [view]
        gender:
            expose: true
            groups: [view]
        address:
            expose: true
            groups: [view]
        webPath:
            expose: true
            groups: [view]
            serialized_name: avatar_url
        role:
            expose: true
            groups: [view]
        createdAt:
            expose: true
            groups: [view]
        updatedAt:
            expose: true
            groups: [view]