CoreBundle\Entity\LikeList:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [view_like_list,view_coupon,view_coupon_list]
        coupon:
            expose : true
            groups: [view_like_list,view_coupon,view_coupon_list]
        app_user_id:
            expose: true
            groups: [view_like_list,view_coupon,view_coupon_list]
