CoreBundle\Entity\AppUser:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [view]
        plainPassword:
            expose : true
            groups: [view]
        name:
            expose: true
            groups: [use_list,view]
        gender:
            expose: true
            groups: [view]
        address:
            expose: true
            groups: [view]
        avatarUrl:
            expose: true
            groups: [view]
        role:
            expose: true
            groups: [view]
        followNumber:
            expose : true
            groups: [view]
        usedNumber:
            expose : true
            groups: [view]
        newsNumber:
            expose : true
            groups: [view]
        createdAt:
            expose: true
            groups: [view]
        updatedAt:
            expose: true
            groups: [view]