CoreBundle\Entity\Category:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [store_category,list_coupon_store]
        name:
            expose : true
            groups: [store_category,list_coupon_store]
        iconUrl:
            expose : true
            groups: [store_category,list_coupon_store]