CoreBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [view]
        plainPassword:
            expose : true
            groups: [view,create_user]
            serialized_name: plainPassword
        fullName:
            expose : true
            groups: [view,create_user]
            serialized_name: fullName
        sex:
            expose: true
            groups: [view,create_user]
        birthday:
            expose: true
            groups: [view,create_user]
        locale:
            expose: true
            groups: [view,create_user]
        temporaryHash:
            expose: true
            groups: [view,create_user]
            serialized_name: temporaryHash
        rememberToken:
            expose: true
            groups: [view,create_user]
            serialized_name: rememberToken
        company:
            expose: true
            groups: [view,create_user]
        address:
            expose: true
            groups: [view,create_user]
        tel:
            expose: true
            groups: [view,create_user]
        imageUser:
            expose: true
            groups: [view,create_user]
            serialized_name: imageUser
        createdAt:
            expose: true
            groups: [view]
        updatedAt:
            expose: true
            groups: [view]