CoreBundle\Entity\Category:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [view_store,list_view]
        name:
            expose : true
            groups: [view_store,list_view]
        icon_url:
            expose: true
            groups: [view_store,list_view]
            serialized_name: icon_url
