CoreBundle\Entity\NewsCategory:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [list_news_category,list]
        name:
            expose : true
            groups: [list_news_category,list]