CoreBundle\Entity\Coupon:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [list_coupon,view,store_coupon]
        title:
            expose: true
            groups: [list_coupon,view,store_coupon]
        imageUrl:
            expose: true
            groups: [list_coupon,view, store_coupon]
        description:
            expose: true
            groups: [list_coupon,view]
        expiredTime:
            expose: true
            groups: [list_coupon,view, store_coupon]
            type: DateTime<'Y-m-d'>
        like:
            expose: true
            groups: [list_coupon,view, store_coupon]
            serialized_name: is_like
        store:
            expose: true
            groups: [list_coupon]
            serialized_name: shop
        needLogin:
            expose: true
            groups: [list_coupon,view, store_coupon]
        canUse:
            expose: true
            groups: [list_coupon,view, store_coupon]
        couponPhotoUrls:
            expose: true
            groups: [list_coupon,view, store_coupon]
            serialized_name: coupon_photo_url
        couponType:
            expose : true
            groups: [list_coupon,view, store_coupon]
        createdAt:
            expose: true
            groups: [list_coupon,view]
        updatedAt:
            expose: true
            groups: [list_coupon,view]