CoreBundle\Entity\UseList:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [view,view_coupon]
        coupon_id:
            expose : true
            groups: [view,view_coupon]
        app_user_id:
            expose: true
            groups: [view,view_coupon]
