CoreBundle\Entity\CouponType:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [view_coupon_type]
        name:
            expose : true
            groups: [create_coupon_type, view_coupon_type]
            description: how many objects to return
        iconUrl:
            expose: true
            groups: [create_coupon_type, view_coupon_type]
            serialized_name: iconUrl
        store:
            expose: true
            groups: [view_coupon_type]
        createdAt:
            expose: true
            groups: [view_coupon_type]
        updatedAt:
            expose: true
            groups: [view_coupon_type]