CoreBundle\Entity\Store:
    exclusion_policy: ALL
    properties:
        id:
            expose : true
            groups: [view, view_coupon_type]
        name:
            expose : true
            groups: [view,create_store,view_coupon_type]
        latitude:
            expose: true
            groups: [view,create_store,view_coupon_type]
        longtitude:
            expose: true
            groups: [view,create_store,view_coupon_type]
        storeType:
            expose: false
            groups: [view,view_coupon_type]
        user:
            expose: true
            groups: [view]
        createdAt:
            expose: true
            groups: [view]
        updatedAt:
            expose: true
            groups: [view]