FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        email:
            expose: true
            groups: [view,create_user]
        username:
            expose : true
            groups: [view,create_user]
        enabled:
            expose : true
            groups: [view,create_user]