FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        email:
            expose: true
            groups: [view]
        username:
            expose : true
            groups: [use_list,view]
        enabled:
            expose : true
            groups: [view]