<?php

namespace CoreBundle\Repository;

/**
 * AdminContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminContactRepository extends \Doctrine\ORM\EntityRepository
{
}
