<?php

namespace CoreBundle\Repository;

/**
 * AppUserProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppUserProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
