<?php

namespace CoreBundle\Repository;

/**
 * CouponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponRepository extends \Doctrine\ORM\EntityRepository
{
}
