<?php

namespace CoreBundle\Repository;

/**
 * CouponPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
