<?php

namespace CoreBundle\Repository;

/**
 * CouponTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
