<?php

namespace CoreBundle\Repository;

/**
 * CouponUserPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponUserPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
