<?php

namespace CoreBundle\Repository;

/**
 * FollowListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowListRepository extends \Doctrine\ORM\EntityRepository
{
}
