<?php

namespace CoreBundle\Repository;

/**
 * LikeListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeListRepository extends \Doctrine\ORM\EntityRepository
{
}
