<?php

namespace CoreBundle\Repository;

/**
 * MessageDeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageDeliveryRepository extends \Doctrine\ORM\EntityRepository
{
}
