<?php

namespace CoreBundle\Repository;

/**
 * NewsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
