<?php

namespace CoreBundle\Repository;

/**
 * NewsPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
