<?php

namespace CoreBundle\Repository;

/**
 * PostPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
