<?php

namespace CoreBundle\Repository;

/**
 * PushSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PushSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
