<?php

namespace CoreBundle\Repository;

/**
 * StoreTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
