<?php

namespace CoreBundle\Repository;

/**
 * StoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends \Doctrine\ORM\EntityRepository
{
}
