<?php

namespace CoreBundle\Repository;

/**
 * StorePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StorePhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
