<?php

namespace CoreBundle\Repository;

/**
 * UseListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UseListRepository extends \Doctrine\ORM\EntityRepository
{
}
