CoreBundle\Entity\AccessToken:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\AccessTokenRepository
    manyToOne:
        appUser:
            targetEntity: AppUser
            inversedBy: accessTokens
            joinColumn:
                name: app_user_id
                referencedColumnName: id
        client:
            targetEntity: Client
            inversedBy: accessTokens
            joinColumn:
                name: client_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    lifecycleCallbacks: {  }
