CoreBundle\Entity\AppUser:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\AppUserRepository
    oneToMany:
        accessTokens:
            targetEntity: AccessToken
            mappedBy: appUser
        refreshTokens:
            targetEntity: RefreshToken
            mappedBy: appUser
        socialProfiles:
            targetEntity: SocialProfile
            mappedBy: appUser
        posts:
            targetEntity: Post
            mappedBy: appUser
        useLists:
            targetEntity: UseList
            mappedBy: appUser
        likeLists:
            targetEntity: LikeList
            mappedBy: appUser
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        temporaryHash:
            type: string
            length: 60
            nullable: TRUE
        androidPushKey:
            type: string
            length: 255
            nullable: TRUE
        applePushKey:
            type: string
            length: 255
            nullable: TRUE
        role:
            type: string
            length: 60
            nullable: TRUE
        name:
            type: string
            length: 100
            nullable: TRUE
        gender:
            type: integer
            nullable: TRUE
        address:
            type: string
            length: 255
            nullable: TRUE
        avatarUrl:
            type: string
            length: 255
            nullable: TRUE
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
