CoreBundle\Entity\AppUser:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\AppUserRepository
    manyToOne:
        store:
            targetEntity: Store
            inversedBy: appUsers
            joinColumn:
                name: store_id
                referencedColumnName: id
    oneToMany:
        socialProfiles:
            targetEntity: SocialProfile
            mappedBy: appUser
            cascade: ["all"]
        posts:
            targetEntity: Post
            mappedBy: appUser
            cascade: ["all"]
        useLists:
            targetEntity: UseList
            mappedBy: appUser
            cascade: ["all"]
        likeLists:
            targetEntity: LikeList
            mappedBy: appUser
            cascade: ["persist"]
        followLists:
            targetEntity: FollowList
            mappedBy: appUser
            cascade: ["persist"]

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        appUserId:
            type: string
            length: 100
        name:
            type: string
            length: 100
            nullable: TRUE
        gender:
            type: integer
            nullable: TRUE
        address:
            type: string
            length: 255
            nullable: TRUE
        company:
            type: string
            length: 255
            nullable: TRUE
        tel:
            type: string
            length: 20
            nullable: TRUE
        avatarUrl:
            type: string
            length: 255
            nullable: TRUE
        facebookId:
            type: string
            length: 255
            nullable: TRUE
        instagramId:
            type: string
            length: 255
            nullable: TRUE
        twitterId:
            type: string
            length: 255
            nullable: TRUE
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
