CoreBundle\Entity\AuthCode:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\AuthCodeRepository
    manyToOne:
        user:
            targetEntity: AppUser
            inversedBy: auth_codes
            joinColumn:
                name: app_user_id
                referencedColumnName: id
        client:
            targetEntity: Client
            inversedBy: auth_codes
            joinColumn:
                name: client_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    lifecycleCallbacks: {  }
