CoreBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\CategoryRepository
    oneToMany:
        stores:
            targetEntity: Store
            mappedBy: category
            cascade: ["all"]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        categoryId:
            type: string
            length: 100
        name:
            type: string
            length: 100
        iconUrl:
            type: string
            length: 255
            nullable: TRUE
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }