CoreBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\CategoryRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        icon_url:
            type: string
            length: 255
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }