CoreBundle\Entity\Coupon:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\CouponRepository
    oneToMany:
        useLists:
            targetEntity: UseList
            mappedBy: coupon
            cascade: ["all"]
        likeLists:
            targetEntity: LikeList
            mappedBy: coupon
            cascade: ["persist"]
        couponPhotos:
            targetEntity: CouponPhoto
            mappedBy: coupon
            cascade: ["persist"]
            orphanRemoval: true
        couponUserPhotos:
            targetEntity: CouponUserPhoto
            mappedBy: coupon
            cascade: ["persist"]
            orphanRemoval: true
    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: coupon
            joinTable:
                name: coupons_tags
                joinColumns:
                    coupon_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    manyToOne:
        store:
            targetEntity: Store
            inversedBy: coupons
            joinColumn:
                name: store_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        couponId:
            type: string
            length: 100
        title:
            type: string
            length: 255
        expiredTime:
            type: datetime
        imageUrl:
            type: string
            length: 255
            nullable: TRUE
        needLogin:
            type: boolean
        hashTag:
            type: text
        type:
            type: integer
        description:
            type: text
            nullable: TRUE
        status:
            type: boolean
        size:
            type: integer
            nullable: TRUE
        impression:
            type: integer
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
