CoreBundle\Entity\Coupon:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\CouponRepository
    oneToMany:
        useLists:
            targetEntity: UseList
            mappedBy: coupon
        likeLists:
            targetEntity: LikeList
            mappedBy: coupon
    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: coupon
            joinTable:
                name: coupons_tags
                joinColumns:
                    coupon_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    manyToOne:
        couponType:
            targetEntity: CouponType
            inversedBy: coupons
            joinColumn:
                name: coupon_type_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: integer
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: TRUE
        startDate:
            type: date
        endDate:
            type: date
        status:
            type: integer
        imageUrl:
            type: string
            length: 255
            nullable: TRUE
        size:
            type: integer
            nullable: TRUE
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
