CoreBundle\Entity\Group:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\GroupRepository
    manyToMany:
        users:
            targetEntity: User
            mappedBy: groups
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    lifecycleCallbacks: {  }
