CoreBundle\Entity\LikeList:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\LikeListRepository
    manyToOne:
        coupon:
            targetEntity: Coupon
            inversedBy: likeLists
            cascade: ["persist"]
            joinColumn:
                name: coupon_id
                referencedColumnName: id
        appUser:
            targetEntity: AppUser
            inversedBy: likeLists
            cascade: ["persist"]
            joinColumn:
                name: app_user_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    lifecycleCallbacks: {  }
