CoreBundle\Entity\MessageDelivery:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\MessageDeliveryRepository
    manyToOne:
        pushSetting:
            targetEntity: PushSetting
            inversedBy: messageDeliveries
            cascade: ["persist"]
            orphanRemoval: true
            joinColumn:
                name: push_setting_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        status:
            type: string
            length: 20
    lifecycleCallbacks: {  }
