CoreBundle\Entity\News:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\NewsRepository
    oneTomany:
        newsPhotos:
            targetEntity: NewsPhoto
            mappedBy: news
            cascade: ["all"]
    manyToOne:
        store:
            targetEntity: Store
            inversedBy: news
            joinColumn:
                name: store_id
                referencedColumnName: id
        newsCategory:
                    targetEntity: NewsCategory
                    inversedBy: news
                    joinColumn:
                        name: news_category_id
                        referencedColumnName: id

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        imageUrl:
            type: string
            length: 255
            nullable: TRUE
        description:
            type: text
            nullable: TRUE
        introduction:
            type: text
            nullable: TRUE
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
