CoreBundle\Entity\Photo:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\PhotoRepository
    oneToMany:
        couponPhotos:
            targetEntity: CouponPhoto
            mappedBy: photo
            cascade: ["persist"]
            orphanRemoval: true
        storePhotos:
            targetEntity: StorePhoto
            mappedBy: photo
        couponUserPhotos:
            targetEntity: CouponUserPhoto
            mappedBy: photo
            cascade: ["persist"]
            orphanRemoval: true
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        imageUrl:
            type: string
            length: 255
        photoId:
            type: string
            length: 100
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
