CoreBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\PostRepository
    oneToMany:
        postPhotos:
            targetEntity: PostPhoto
            mappedBy: post
            cascade: ["persist","remove"]
            orphanRemoval: true
        useLists:
            targetEntity: UseList
            mappedBy: post
            cascade: ["all"]
    manyToOne:
        appUser:
            targetEntity: AppUser
            inversedBy: posts
            joinColumn:
                name: app_user_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        message:
            type: text
        hashTags:
            type: text
        snsId:
            type: string
            length: 100
        type:
            type: integer
        postId:
            type: string
            length: 100
        createdTime:
            type: datetime
        status:
            type: integer
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
        url:
            type: string
            length: 255
    lifecycleCallbacks: {  }
