CoreBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\PostRepository
    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: posts
            joinTable:
                name: posts_tags
                joinColumns:
                    post_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    manyToOne:
        appUser:
            targetEntity: AppUser
            inversedBy: posts
            joinColumn:
                name: app_user_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        socialUserId:
            type: integer
        socialMediaId:
            type: string
            length: 50
        caption:
            type: string
            length: 200
        description:
            type: text
            nullable: TRUE
        createdTime:
            type: datetime
        status:
            type: integer
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
        socialUserName:
            type: string
            length: 100
        socialAvatar:
            type: string
            length: 255
        imageUrl:
            type: string
            length: 255
        url:
            type: string
            length: 255
    lifecycleCallbacks: {  }
