CoreBundle\Entity\PushSetting:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\PushSettingRepository
    oneToMany:
        messageDeliveries:
            targetEntity: MessageDelivery
            mappedBy: pushSetting
            cascade: ["persist"]
            orphanRemoval: true
    manyToOne:
        store:
            targetEntity: Store
            inversedBy: pushSettings
            joinColumn:
                name: store_id
                referencedColumnName: id

        segement:
            targetEntity: Segement
            inversedBy: pushSettings
            joinColumn:
                name: segement_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        message:
            type: string
            length: 255
        json:
            type: string
            length: 20
        status:
            type: string
            length: 20
        type:
            type: string
            length: 10
        deliveryTime:
            type: datetime
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
