CoreBundle\Entity\PushSetting:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\PushSettingRepository
    manyToOne:
        store:
            targetEntity: Store
            inversedBy: pushSettings
            joinColumn:
                name: store_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        message:
            type: string
            length: 255
        segment:
            type: string
            length: 100
        status:
            type: string
            length: 20
        notificationId:
            type: string
            length: 100
            nullable: TRUE
        recipientTotal:
            type: integer
            nullable: TRUE
        type:
            type: string
            length: 10
        deliveryTime:
            type: datetime
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
