CoreBundle\Entity\Segement:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\SegmentRepository
    oneToMany:
        pushSettings:
            targetEntity: PushSetting
            mappedBy: segement
            cascade: ["all"]
    manyToOne:
        store:
            targetEntity: Store
            inversedBy: segements
            joinColumn:
                name: store_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
