CoreBundle\Entity\SocialProfile:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\SocialProfileRepository
    manyToOne:
        appUser:
            targetEntity: AppUser
            inversedBy: socialProfiles
            cascade: ["all"]
            joinColumn:
                name: app_user_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        socialType:
            type: integer
        socialId:
            type: string
            length: 255
        socialToken:
            type: text
            length: 255
        socialSecret:
            type: string
            length: 255
            nullable: TRUE
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
