CoreBundle\Entity\Store:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\StoreRepository
    oneToMany:
        followLists:
            targetEntity: FollowList
            mappedBy: store
        pushSettings:
            targetEntity: PushSetting
            mappedBy: store
        news:
            targetEntity: News
            mappedBy: store
        coupons:
            targetEntity: Coupon
            mappedBy: store
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: stores
            joinColumn:
                name: category_id
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: stores
            joinColumn:
                name: user_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        latitude:
            type: string
            length: 20
        longtitude:
            type: string
            length: 20
        avatarUrl:
            type: string
            length: 255
        tel:
            type: string
            length: 255
        address:
            type: string
            length: 255
        closeDate:
            type: string
            length: 255
        aveBill:
            type: integer
        helpText:
            type: string
            length: 255
        shopPhotoUrl:
            type: string
            length: 255
        operationStartTime:
            type: datetime
        operationEndTime:
            type: datetime
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
