CoreBundle\Entity\Store:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\StoreRepository
    oneToMany:
        followLists:
            targetEntity: FollowList
            mappedBy: store
            cascade: ["persist"]
        pushSettings:
            targetEntity: PushSetting
            mappedBy: store
            cascade: ["all"]
        segements:
            targetEntity: Segement
            mappedBy: store
            cascade: ["all"]
        news:
            targetEntity: News
            mappedBy: store
            cascade: ["all"]
        coupons:
            targetEntity: Coupon
            mappedBy: store
            cascade: ["all"]
        storePhotos:
            targetEntity: StorePhoto
            mappedBy: store
            cascade: ["persist"]
            orphanRemoval: true
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: stores
            joinColumn:
                name: category_id
                referencedColumnName: id
        appUser:
            targetEntity: AppUser
            inversedBy: stores
            joinColumn:
                name: app_user_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        storeId:
            type: string
            length: 100
        title:
            type: string
            length: 255
        operationStartTime:
            type: datetime
        operationEndTime:
            type: datetime
        avatarUrl:
            type: string
            length: 255
        impression:
            type: integer
        tel:
            type: string
            length: 20
        latitude:
            type: string
            length: 20
        longitude:
            type: string
            length: 20
        address:
            type: string
            length: 255
        closeDate:
            type: string
            length: 255
            nullable: TRUE
        aveBill:
            type: integer
            nullable: TRUE
        helpText:
            type: text
            nullable: TRUE
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
