CoreBundle\Entity\Store:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\StoreRepository
    oneToMany:
        followLists:
            targetEntity: FollowList
            mappedBy: store
            cascade: ["all"]
        pushSettings:
            targetEntity: PushSetting
            mappedBy: store
            cascade: ["all"]
        news:
            targetEntity: News
            mappedBy: store
            cascade: ["all"]
        coupons:
            targetEntity: Coupon
            mappedBy: store
            cascade: ["all"]
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: stores
            joinColumn:
                name: category_id
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: stores
            joinColumn:
                name: user_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        operationStartTime:
            type: datetime
        operationEndTime:
            type: datetime
        avatarUrl:
            type: string
            length: 255
        tel:
            type: string
            length: 20
        latitude:
            type: string
            length: 20
        longitude:
            type: string
            length: 20
        address:
            type: string
            length: 255
        closeDate:
            type: string
            length: 255
        aveBill:
            type: integer
        help_text:
            type: text
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
