CoreBundle\Entity\Store:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\StoreRepository
    oneToMany:
        pushSettings:
            targetEntity: PushSetting
            mappedBy: store
        news:
            targetEntity: News
            mappedBy: store
        coupons:
            targetEntity: Coupon
            mappedBy: store
    manyToOne:
        user:
            targetEntity: User
            inversedBy: stores
            joinColumn:
                name: user_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        latitude:
            type: string
            length: 20
        longtitude:
            type: string
            length: 20
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
