CoreBundle\Entity\UseList:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\UseListRepository
    manyToOne:
        coupon:
            targetEntity: Coupon
            inversedBy: useLists
            cascade: ["all"]
            joinColumn:
                name: coupon_id
                referencedColumnName: id
        appUser:
            targetEntity: AppUser
            inversedBy: useLists
            cascade: ["all"]
            joinColumn:
                name: app_user_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        status:
            type: integer
        code:
            type: string
            length: 100
        expiredTime:
            type: datetime
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    lifecycleCallbacks: {  }
