CoreBundle\Entity\UseList:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\UseListRepository
    manyToOne:
        coupon:
            targetEntity: Coupon
            inversedBy: useLists
            joinColumn:
                name: coupon_id
                referencedColumnName: id
        appUser:
            targetEntity: AppUser
            inversedBy: useLists
            joinColumn:
                name: app_user_id
                referencedColumnName: id
        store:
            targetEntity: Store
            inversedBy: useLists
            joinColumn:
                name: store_id
                referencedColumnName: id
        category:
            targetEntity: Category
            inversedBy: useLists
            joinColumn:
                name: category_id
                referencedColumnName: id

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        status:
            type: integer
        createdAt:
            type: datetime
        usedAt:
            type: datetime
    lifecycleCallbacks: {  }
