CoreBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: CoreBundle\Repository\UserRepository
    oneToMany:
        stores:
            targetEntity: Store
            mappedBy: user
    manyToMany:
        groups:
            targetEntity: Group
            inversedBy: users
            joinTable:
                name: users_groups
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fullName:
            type: string
            length: 255
        sex:
            type: integer
        birthday:
            type: date
        locale:
            type: string
            length: 5
        temporaryHash:
            type: string
            length: 60
        rememberToken:
            type: string
            length: 100
        company:
            type: string
            length: 255
        address:
            type: string
            length: 255
        tel:
            type: string
            length: 20
        imageUser:
            type: string
            length: 255
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        deletedAt:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks: {  }
